Cootpla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GestorApp.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GestorApp/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView


urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"), name="redirect-admin"),
    path('login', auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True),name='login'),
    path('login_user', views.login_user, name="login-user"),
    path('registrarUsuario', views.registrarUsuario, name="registrar-usuario"),
    path('logout', views.logoutuser, name='logout'),

    path('perfil', views.perfil, name='perfil'),
    path('actualizarPerfil', views.actualizarPerfil, name='actualizar_perfil'),
    path('actualizarContrasena', views.actualizarContrasena, name='actualizar_contrasena'),


    path('', views.inicio, name='inicio'),

    path('sede', views.sede, name='sede-pagina'),
    path('adm_sede', views.adm_sede, name='adm-sede'),
    path('guardar_sede', views.guardar_sede, name='guardar-sede'),
    path('adm_sede/<int:pk>', views.adm_sede, name='adm-sede-pk'),
    path('eliminar_sede', views.eliminar_sede, name='eliminar-sede'),


    path('bus', views.bus, name='bus-pagina'),
    path('adm_bus', views.adm_bus, name='adm-bus'),
    path('guardar_bus', views.guardar_bus, name='guardar-bus'),
    path('adm_bus/<int:pk>', views.adm_bus, name='adm-bus-pk'),
    path('eliminar_bus', views.eliminar_bus, name='eliminar-bus'),

   #

    path('programacion', views.programacion, name='programacion-pagina'),
    path('adm_programacion', views.adm_programacion, name='adm-programacion'),
    path('guardar_programacion',views.guardar_programacion,name='guardar-programacion'),
    path('adm_programacion/<int:pk>',views.adm_programacion,name='adm-programacion-pk'),
    path('eliminar_programacion', views.eliminar_programacion, name='eliminar-programacion'),
    #

    path('encomienda', views.encomienda, name='encomienda-pagina'),
    path('adm_encomienda', views.adm_encomienda, name='adm-encomienda'),
    path('guardar_encomienda',views.guardar_encomienda,name='guardar-encomienda'),
    path('adm_encomienda/<int:pk>',views.adm_encomienda,name='adm-encomienda-pk'),
    path('eliminar_encomienda', views.eliminar_encomienda, name='eliminar-encomienda'),

    #

    path('viajes_programados',views.viajes_programados,name='viajes-programados-pagina'),

    path('buscar_programado', views.buscar_programado, name='buscar-viaje-programado'),

    path('', views.base),

    path('contacto', views.contacto, name="contacto"),
]

GestorApp/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator


class Conductor(models.Model): #
    conductor = models.CharField(max_length=100)
    codigo = models.CharField(max_length=100)
    cedula = models.CharField(max_length=100)
    estado = models.CharField(max_length=2, choices=(('1', 'Activo'), ('2', 'Inactivo')), default=1)

    def __str__(self):
        return str(self.conductor + ' - ' + self.codigo)

    class Meta:
        verbose_name_plural = 'Conductores'


class Propietario(models.Model):
    propietario = models.CharField(max_length=100)
    documento = models.CharField(max_length=12)
    estado = models.CharField(max_length=2, choices=(('1', 'Activo'), ('2', 'Inactivo')), default=1)

    def __str__(self):
        return str(self.propietario)

    class Meta:
        verbose_name_plural = 'Propietarios'


class Sede(models.Model):
    sede = models.CharField(max_length=250)
    tipo = models.CharField(max_length=2, choices=(('1','Terminal'),('2','Oficina'),('3','Paradero')), default='1')
    fecha_creado = models.DateTimeField(default=timezone.now)
    fecha_actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.sede


class Bus(models.Model):
    propietario = models.ForeignKey(Propietario, on_delete=models.CASCADE, blank=True, null=True)
    numero_bus = models.CharField(max_length=5)
    placa_bus = models.CharField(max_length=8)
    asientos = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(50)])
    estado = models.CharField(max_length=2, choices=(('1', 'Activo'), ('2', 'Inactivo'), ), default=1)
    fecha_creado = models.DateTimeField(default=timezone.now)
    fecha_actualizado = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name_plural = 'Buses'

    def __str__(self):
        return self.numero_bus


class Programacion(models.Model):
    codigo = models.CharField(max_length=100)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    origen = models.ForeignKey(Sede, on_delete=models.CASCADE, related_name='origen')
    destino = models.ForeignKey(Sede, on_delete=models.CASCADE, related_name='destino')
    programacion = models.DateTimeField()
    precio = models.IntegerField(default=0, validators=[MinValueValidator(5000), MaxValueValidator(75000)])
    estado = models.CharField(max_length=2, choices=(('0','Cancelado'),('1','Despachado')), default=1)
    fecha_creado = models.DateTimeField(default=timezone.now)
    fecha_actualizado = models.DateTimeField(auto_now=True)


    def __str__(self):
        return str(self.codigo + ' - ' + self.bus.numero_bus)

    class Meta:
        verbose_name_plural = 'Programación'


class Encomienda(models.Model):
    programacion = models.ForeignKey(Programacion, on_delete=models.CASCADE)
    nombre_envio = models.CharField(max_length=100)
    cedula_envio = models.CharField(max_length=12)
    telefono_envio = models.CharField(max_length=12)
    nombre_recibido = models.CharField(max_length=100)
    cedula_recibido = models.CharField(max_length=12)
    telefono_recibido = models.CharField(max_length=12)
    codigo_encomienda = models.CharField(max_length=5)
    #costo_envio
    caracteristicas = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1000), MaxValueValidator(100000)])
    estado = models.CharField(max_length=2, choices=(('1', 'Programada'), ('2', 'Entregada')), default=1)
    fecha_creado = models.DateTimeField(default=timezone.now)
    fecha_actualizado = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.nombre_envio

GestorApp/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.core.management import call_command

from django.shortcuts import render,redirect
import json
from django.contrib import messages
from django.http import HttpResponse,HttpRequest
from .forms import RegistrarUsuario, ActualizarPerfil,ActualizarContrasena,GuardarSede, GuardarBus,GuardarProgramacion, GuardarEncomienda
from .models import Sede, Bus, Programacion, Encomienda,Propietario, Conductor

from datetime import datetime

from django.db.models import Q, QuerySet

from django.utils import timezone

context = {
    'page_title' : 'Visor de Viajes Intermunicipales',
}


def login_user(request):
    logout(request)
    resp = {"status":'failed','msg':''}
    username = ''
    password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                resp['status']='success'
            else:
                resp['msg'] = "Usuario o Contraseña: Incorrecta"
        else:
            resp['msg'] = "Usuario o Contraseña: Incorrecta"
    return HttpResponse(json.dumps(resp),content_type='application/json')

@login_required
def inicio(request: HttpRequest):
    context = {}
    context['page_title'] = 'Inicio'
    context['buses'] = Bus.objects.count()
    context['encomiendas'] = Encomienda.objects.count()
    context['programaciones'] = Programacion.objects.filter(estado= 1, programacion__gt = datetime.today()).count()
    context['username'] = User.objects.count()

    labels = []
    data = []
  
    queryset = Bus.objects.order_by('estado')
    for buses_c in queryset:
        if buses_c.estado == '1':
            labels.append(buses_c.numero_bus)
            data.append(buses_c.asientos)       

    context = {
        'labels': labels,
        'data': data,
    }


    return render(request,'inicio.html',context)



def logoutuser(request: HttpRequest):
    logout(request)
    return redirect('/')


@login_required
def registrarUsuario(request: HttpRequest):
    user = request.user
    context['page_title'] = "Registrar Usuario"
    if request.method == 'POST':
        data = request.POST.copy()
        form = RegistrarUsuario(data)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pwd = form.cleaned_data.get('password1')
            loginUser = authenticate(username= username, password = pwd)
            login(request, loginUser)
            return redirect('inicio')
        else:
            context['reg_form'] = form
    return render(request,'registro.html',context)


@login_required
def perfil(request: HttpRequest):
    context['page_title'] = 'Pelfil del Usuario'
    return render(request, 'perfil.html',context)


@login_required
def actualizarPerfil(request: HttpRequest):
    context['page_title'] = 'Actualizar Perfil'
    user = User.objects.get(id=request.user.id)
    if not request.method == 'POST':
        form = ActualizarPerfil(instance=user)
        context['form'] = form
        print(form)
    else:
        form = ActualizarPerfil(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Perfil actualizado correctamente")
            return redirect("perfil")
        else:
            context['form'] = form

    return render(request, 'gestion_perfil.html', context)


@login_required
def actualizarContrasena(request: HttpRequest):
    context['page_title'] = "Actualizar Contraseña"
    if request.method == 'POST':
        form = ActualizarContrasena(user = request.user, data= request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Contraseña actualizada correctamente")
            update_session_auth_hash(request, form.user)
            return redirect("perfil")
        else:
            context['form'] = form
    else:
        form = ActualizarContrasena(request.POST)
        context['form'] = form
    return render(request,'actualizar_contrasena.html',context)


@login_required
def sede(request: HttpRequest):
    semaforo = {
        '1': 'bg-primary',
        '2': 'bg-secondary',
        '3': 'bg-success',
    }
    context['page_title'] = "Sedes"
    sedes = Sede.objects.all()
    context['sedes'] = sedes
    context['semaforo'] = semaforo
    return render(request, 'sede.html', context)


@login_required
def guardar_sede(request: HttpRequest):
    resp = {'status': 'failed', 'msg': ''}
    if request.method == 'POST':
        id_value = request.POST.get('id')
        if id_value and id_value.isnumeric():
            sede = Sede.objects.get(pk=id_value)
        else:
            sede = None
        if sede is None:
            form = GuardarSede(request.POST)
        else:
            form = GuardarSede(request.POST, instance=sede)
        if form.is_valid():
            form.save()
            messages.success(request, 'La Sede se ha guardado exitosamente.')
            resp['status'] = 'success'
        else:
            for fields in form:
                for error in fields.errors:
                    resp['msg'] += str(error + "<br>")
    else:
        resp['msg'] = 'No se han guardado datos.'
    return HttpResponse(json.dumps(resp), content_type='application/json')


@login_required
def adm_sede(request: HttpRequest, pk: str | None = None):
    context['page_title'] = "Gestion de Sedes"
    if pk != None:
        sede = Sede.objects.get(id=pk)
        context['sede'] = sede
    else:
        context['sede'] = {}

    return render(request, 'adm_sede.html', context)


@login_required
def eliminar_sede(request: HttpRequest):
    resp = {'status': 'failed', 'msg': ''}

    if request.method == 'POST':
        try:
            sede = Sede.objects.get(id=request.POST['id'])
            sede.delete()
            messages.success(request, 'La Sede se ha eliminado exitosamente')
            resp['status'] = 'success'
        except Sede.DoesNotExist as err:
            resp['msg'] = 'La Sede no se pudo eliminar'
            print(err)

    else:
        resp['msg'] = 'La Sede no se pudo eliminar'

    return HttpResponse(json.dumps(resp), content_type="application/json")


# bus
@login_required
def bus(request: HttpRequest):
    context['page_title'] = "Buses"
    buses = Bus.objects.all()
    context['buses'] = buses
    return render(request, 'bus.html', context)

@login_required
def guardar_bus(request:HttpRequest):
    resp = {'status': 'failed', 'msg': ''}
    if request.method == 'POST':
        id_value = request.POST.get('id')
        if id_value and id_value.isnumeric():
            bus = Bus.objects.get(pk=id_value)
        else:
            bus = None
        if bus is None:
            form = GuardarBus(request.POST)
        else:
            form = GuardarBus(request.POST, instance=bus)
        if form.is_valid():
            form.save()
            messages.success(request, 'El Bus se ha guardado exitosamente')
            resp['status'] = 'success'
        else:
            for fields in form:
                for error in fields.errors:
                    resp['msg'] += str(error + "<br>")
    else:
        resp['msg'] = 'No se han guardado datos.'
    return HttpResponse(json.dumps(resp), content_type='application/json')




# @login_required
# def guardar_bus(request: HttpRequest):
#     resp = {'status': 'failed', 'msg': ''}
#     if request.method == 'POST':
#         form = GuardarBus(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'El Bus se ha guardado exitosamente')
#             resp['status'] = 'success'
#         else:
#             for fields in form:
#                 for error in fields.errors:
#                     resp['msg'] += str(error + "<br>")
#     else:
#         resp['msg'] = 'No se han guardado datos.'
#     return HttpResponse(json.dumps(resp), content_type='application/json')


@login_required
def adm_bus(request: HttpRequest, pk: str | None = None):
    context['page_title'] = "Gestión de Buses"
    propietarios = Propietario.objects.all()
    context['propietarios'] = propietarios
    
    if pk != None:
        bus = Bus.objects.get(id=pk)
        context['bus'] = bus
    else:
        context['bus'] = {}

    return render(request, 'adm_bus.html', context)


@login_required
def eliminar_bus(request: HttpRequest):
    resp = {'status': 'failed', 'msg': ''}
    print(f"datos: {request}")
    if request.method == 'POST':
        
        try:
            bus = Bus.objects.get(id=request.POST['id'])
            bus.delete()
            messages.success(request, 'El Bus se ha guardado exitosamente.')
            resp['status'] = 'success'
        except Bus.DoesNotExist as err:
            resp['msg'] = 'El Bus no se pudo eliminar'
            print(err)
    else:
        resp['msg'] = 'El Bus no se pudo eliminar'
    return HttpResponse(json.dumps(resp), content_type="application/json")


@login_required
def programacion(request: HttpRequest):
    context['page_title'] = "Progamación"
    programaciones = Programacion.objects.all()
    context['programaciones'] = programaciones
    return render(request, 'programacion.html', context)


@login_required
def guardar_programacion(request: HttpRequest):
    resp = {'status':'failed','msg':''}
    if request.method == 'POST':
        form = GuardarProgramacion(request.POST)
        if form.is_valid():
            programacion = form.save(commit=False)
            # convierte la hora a la zona horaria por defecto
            programacion.programacion = timezone.make_aware(programacion.programacion, timezone.get_default_timezone())

GestorApp/templates/actualizar_contrasena.html
{% extends 'base.html' %}{% load static %}{% block Contenido %}
<style>
    .errorlist {
        color: var(--bs-danger)
    }
</style>
<div class="row justify-content-center">
    <div class="col-lg-5 col-md-7 col-sm-12 col-xs-12">
        <div class="card card-default rounded-0 shadow">
            <div class="card-header">
                <h4 class="card-title"><b>Actualizar Contraseña</b></h4>
            </div>
            <div class="card-body">
                <div class="container-fluid">
                    <form id="register-user" method="POST" action="{% url 'actualizar_contrasena' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mdc-layout-grid">
                            <div class="mdc-layout-grid__inner">
                                {{ form.as_p }}
                                <div class="form-group mb-3">
                                    <div class="d-flex w-100 justify-content-end">
                                        <button class="btn btn-sm rounded-0 btn-primary col-4">
                                                Actualizar
                                            </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock Contenido %}

GestorApp/templates/adm_encomienda.html
{% load customfilter %}
{% load humanize %}

<div class="container-fluid">
     <form action=" " id="encomienda-form">
     {% csrf_token %}
        <div class="form-group">
            <label for="programacion"  id="programacion" class="control-label">Viaje Programado</label>
            <select name="programacion"  class="form-select select2 rounded-0">
                    {% if not encomienda.programacion %}  
                        {% for encomienda in encomiendas %}
                        <option value="{{ encomienda.id }}" >{{ encomienda.programacion }} </option>
                        {% endfor %}
                    {% else %}
                    <option ></option>
                    {% endif %}
                    {% for programacion in programaciones %}
                    {% if encomienda.programacion.id == encomienda.id %}
                    <option value="{{ programacion.id }}" selected>{{ programacion }}</option>
                    {% else %}
                    <option value="{{ programacion.id }}" >{{ programacion }}</option>
                    {% endif %}
                    {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="nombre_envio"  id="nombre_envio" class="control-label"> Nombre Remitente:</label>
            <input class="form-control rounded-0" name="nombre_envio" type="text" value="{{ encomienda.nombre_envio}}" required>
        </div>
        <div class="form-group">
            <label for="cedula_envio"  id="cedula_envio" class="control-label">Documento:</label>
            <input class="form-control rounded-0" name="nombre_envio"  type="number" value="{{ encomienda.cedula_envio}}" required>
        </div>
        <div class="form-group">
            <label for="telefono_envio"  id="telefono_envio" class="control-label">Telefono:</label>
            <input class="form-control rounded-0" name="telefono_envio" type="number" value="{{ encomienda.telefono_envio}}" required>
        </div>
        <div class="form-group">
            <label for="nombre_recibido"  id="nombre_recibido" class="control-label">Nombre de quién reclama la encomienda:</label>
            <input class="form-control rounded-0" name="nombre_recibido" type="text" value="{{ encomienda.nombre_recibido}}" required>
        </div>
        <div class="form-group">
            <label for="cedula_recibido"  id="cedula_recibido" class="control-label">Telefono de quién reclama la encomienda:</label>
            <input class="form-control rounded-0" name="nombre_recibido" type="number" value="{{ encomienda.cedula_recibido}}" required>
        </div>
        <div class="form-group">
            <label for="caracteristicas" class="control-label">Costo de Envio</label>
            <input type="text" class="form-control rounded-0" id="caracteristicas" name="caracteristicas"  value="{{  encomienda.caracteristicas }}" required>
        </div>
{#          FECHA Y CODIGO ASIGNADO#}

        <div class="form-group mb-3 ">
         <label for="encomienda" class="control-label">:</label>
            <select name="encomienda" id="encomienda" class="form-select rounded-0">
                {% if not encomienda.estado or encomienda.estado == '1' %}
                <option value="1" selected>Programado</option>
                {% else %}
                <option value="1">Programado</option>
                {% endif %}
                {% if encomienda.estado == '0' %}
                <option value="2" selected>Entregado</option>
                {% else %}
                <option value="2" selected>Entregrado</option>
                {% endif %}
            </select>
        </div>
    </form>
</div>
    <script>
    $(function() {
         $('.select2').select2({
            width:"100%",
            placeholder: "Por favor seleccione aquí",
            dropdownParent:$('#uni_modal')
        })


        $('#encomienda-form').submit(function(e) {
            e.preventDefault();
            var _this = $(this)
            $('.err-msg').remove();
            var el = $('<div>')
            el.addClass("alert alert-danger err-msg")
            el.hide()
            if (_this[0].checkValidity() == false) {
                _this[0].reportValidity();
                return false;
            }
            start_loader();
            $.ajax({
                url: "{% url 'guardar-encomienda' %}",
                data: new FormData($(this)[0]),
                cache: false,
                contentType: false,
                processData: false,
                method: 'POST',
                type: 'POST',
                dataType: 'json',
                error: err => {
                    console.log(err)
                    alert("An error occured ", 'error');
                    end_loader();
                },
                success: function(resp) {
                    if (typeof resp == 'object' && resp.status == 'success') {
                        el.removeClass("alert alert-danger err-msg ")
                        location.reload()
                    } else if (resp.status == 'failed' && !!resp.msg) {
                        el.html(resp.msg)
                    } else {
                        el.text("An error occured ", 'error');
                        end_loader();
                        console.err(resp)
                    }
                    _this.prepend(el)
                    el.show('slow')
                    $("html, body, .modal ").scrollTop(0);
                    end_loader()
                }
            })
        })
    })
</script>

GestorApp/templates/sede.html
{% extends 'base.html' %}
{% load humanize %}
{% block Contenido %}
{% load customfilter %}

    <div class="container-fluid">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card card-default table-responsive">
                <div class="card-header">
                    <h7>Ingrese las Sedes(terminales, sucursales o paradas) habilitadas para recoger y bajar pasajeros:</h7>
                    <div class="d-flex w-100 align-items-center justify-content-between">
                        <h4 class="card-title fw-bold text-wrap">Sedes</h4>
                        <div class="tools">
                            <button type="button" class="btn btn-primary rounded-0 bg-gradient btn-sm" id='adiccion'><i class="fa fa-plus"></i>Adicionar</button>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="container-fluid table-responsive" >
                        <table class="table table-bordered" id="sede-list">
                            <thead>
                            <tr class="bg-gradient bg-secondary bg-opacity-50 text-light">
                                <th class="px-2 py-2 text-center">#</th>
                                <th class="px-2 py-2 text-center">Fecha de Creación</th>
                                <th class="px-2 py-2 text-center">Sede</th>
                                <th class="px-2 py-2 text-center">Tipo</th>
                                <th class="px-2 py-2 text-center">Acción</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for sede in sedes %}
                                <tr>
                                    <td class="px-2 py-1 align-middle">{{ forloop.counter }}</td>
                                    <td class="px-2 py-1 align-middle">{{ sede.fecha_creado }}</td>
                                    <td class="px-2 py-1 align-middle">{{ sede.sede }}</td>

                                    <td class="px-1 py-1 align-middle text-center">
                                <span class="badge {{ semaforo|dict_key:sede.tipo}} bg-gradient rounded-pill px-2">
                                    {{ sede.get_tipo_display }}
                                </span>
                                    </td>

                                    <td class="px-2 py-1 align-middle text-center">
                                        <a class="btn btn-outline-primary btn-sm edit-data" href="javascript:void(0)" data-id="{{ sede.pk }}" title="Editar">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <button class="btn btn-outline-danger btn-sm delete-data" type="button" data-id="{{ sede.pk }}" title="Eliminar">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock Contenido %} {% block ScriptBlock %}
    <script>
        $(function() {
            $('#adiccion').click(function() {
                uni_modal('<i class="fa fa-plus"></i> Adicionar Sede', '{% url "adm-sede" %}', 'modal-md')
            })
            $('.edit-data').click(function() {
                uni_modal('<i class="fa fa-edit"></i> Editar Sede', '{% url "adm-sede" %}/' + $(this).attr('data-id'), 'modal-md')
            })
            $('.delete-data').click(function() {
                _conf("¿Deseas eliminar esta Empresa del sistema?", "eliminar_sede", [$(this).attr('data-id')])
            })

            $('#sede-list').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: 4
                }],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                initComplete: function(settings, json) {
                    $('table td, table th').addClass('px-2 py-1')
                },
                drawCallback: function(settings) {
                    $('table td, table th').addClass('px-2 py-1')
                }
            })
        })

        function eliminar_sede($id) {
            start_loader();
            var _this = $(this)
            $('.err-msg').remove();
            var el = $('<div>')
            el.addClass("alert alert-danger err-msg")
            el.hide()
            $.ajax({
                url: '{% url "eliminar-sede" %}',
                headers: {
                    'X-CSRFToken': "{{csrf_token}}"
                },
                method: 'POST',
                data: {
                    id: $id
                },
                dataType: 'json',
                error: err => {
                    console.log(err)
                    el.text('An error occurred.')
                    el.show('slow')
                    end_loader()
                },
                success: function(resp) {
                    if (resp.status == 'success') {
                        sede.reload()
                    } else if (!!resp.msg) {
                        el.text('An error occurred.')
                        el.show('slow')
                    } else {
                        el.text('An error occurred.')
                        el.show('slow')
                    }
                    end_loader()
                }
            })
        }
    </script>
{% endblock ScriptBlock %}